name: Deploy Production
run-name: Deploy ${{ github.ref_name }}

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    uses: matt-fff/urlup-be-infra/.github/workflows/deploy-prod.yml@mw/reuse-wf
    secrets: inherit
