name: Preview Pull Request
run-name: Preview ${{ github.ref_name }}

on:
  push:
    branches:
      - trunk-merge/**
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    uses: matt-fff/urlup-be-infra/.github/workflows/preview-pr.yml@mw/reuse-wf
    secrets: inherit
